config/routes.rb
Mvp::Application.routes.draw do

  resources :keywords do 
    	member do
        get :vote_up
        get :vote_down
      end
  end
 
  get "pages/about"
  get "pages/test"
  get "pages/test2"
  get "jobs/autopilot"
  match "/about" => "pages#about"
  match "/apply" => "jobs#index"


  resources :jobs do

  	member do 
  		get 'mcdm'
      get 'autopilot'
  		match 'apply' => "candidates#new"
      match 'autopilot' => "jobs#autopilot"
  	end

  	resources :candidates do
        resources :comments 
  		member do

        get :vote_up
        get :vote_down
      end
    end

    resources :criteria do 
  		member do
        get :vote_up
        get :vote_down
      end
    end
  end

  authenticated :user do
    root :to => 'jobs#index'
  end
  root :to => "users#show"
  devise_for :users
  resources :users, :only => :show

  
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController
  # GET /criteria
  # GET /criteria.json
  def index
    @criteria = Criterium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @criteria }
    end
  end

  # GET /criteria/1
  # GET /criteria/1.json
  def show
    @criterium = Criterium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @criterium }
    end
  end

  # GET /criteria/new
  # GET /criteria/new.json
  def new
    @criterium = Criterium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @criterium }
    end
  end

  # GET /criteria/1/edit
  def edit
    @criterium = Criterium.find(params[:id])
  end

  # POST /criteria
  # POST /criteria.json
  def create
    @criterium = Criterium.new(params[:criterium])

    respond_to do |format|
      if @criterium.save
        format.html { redirect_to @criterium, notice: 'Criterium was successfully created.' }
        format.json { render json: @criterium, status: :created, location: @criterium }
      else
        format.html { render action: "new" }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /criteria/1
  # PUT /criteria/1.json
  def update
    @criterium = Criterium.find(params[:id])

    respond_to do |format|
      if @criterium.update_attributes(params[:criterium])
        format.html { redirect_to @criterium, notice: 'Criterium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criteria/1
  # DELETE /criteria/1.json
  def destroy
    @criterium = Criterium.find(params[:id])
    @criterium.destroy

    respond_to do |format|
      format.html { redirect_to criteria_url }
      format.json { head :no_content }
    end
  end
  
  def vote_up
    @criterium = Criterium.find(params[:id])
    @criterium.inc(:weight, 1)
    redirect_to mcdm_job_url(params[:job_id]), :notice => "Vote up is successfully submitted."
  end
  
  def vote_down
    @criterium = Criterium.find(params[:id])
    @criterium.inc(:weight, -1)
    redirect_to mcdm_job_url(params[:job_id]), :notice => "Vote up is successfully submitted."
  end
  
 	def cat 
 		1
 	end
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/views/criteria/_form.html.erb
<%= form_for(@criterium) do |f| %>
  <% if @criterium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@criterium.errors.count, "error") %> prohibited this criterium from being saved:</h2>

      <ul>
      <% @criterium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/criteria/edit.html.erb
<h1>Editing criterium</h1>

<%= render 'form' %>

<%= link_to 'Show', @criterium %> |
<%= link_to 'Back', criteria_path %>

app/views/criteria/index.html.erb
<h1>Listing criteria</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @criteria.each do |criterium| %>
  <tr>
    <td><%= link_to 'Show', criterium %></td>
    <td><%= link_to 'Edit', edit_criterium_path(criterium) %></td>
    <td><%= link_to 'Destroy', criterium, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Criterium', new_criterium_path %>

app/views/criteria/new.html.erb
<h1>New criterium</h1>

<%= render 'form' %>

<%= link_to 'Back', criteria_path %>

app/views/criteria/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_criterium_path(@criterium) %> |
<%= link_to 'Back', criteria_path %>