config/routes.rb
Mvp::Application.routes.draw do

  resources :keywords do 
    	member do
        get :vote_up
        get :vote_down
      end
  end
 
  get "pages/about"
  get "pages/test"
  get "pages/test2"
  get "jobs/autopilot"
  match "/about" => "pages#about"
  match "/apply" => "jobs#index"


  resources :jobs do

  	member do 
  		get 'mcdm'
      get 'autopilot'
  		match 'apply' => "candidates#new"
      match 'autopilot' => "jobs#autopilot"
  	end

  	resources :candidates do
        resources :comments 
  		member do

        get :vote_up
        get :vote_down
      end
    end

    resources :criteria do 
  		member do
        get :vote_up
        get :vote_down
      end
    end
  end

  authenticated :user do
    root :to => 'jobs#index'
  end
  root :to => "users#show"
  devise_for :users
  resources :users, :only => :show

  
end

app/models/job.rb
class Job
  include Mongoid::Document
  field :title, :type => String
  field :description, :type => String
  field :evaluated_candidate, :type => Integer, :default => 1
  has_many :candidates
  has_many :criteria

  def next_candidate(candidates,job)

    #@next_candidate=Candidate.first(:conditions => ['id > ?', self.id], :order => 'id ASC')

      
    #@next_candidate=candidates.desc(:score).limit(1).first
		
	  return @next_candidate
  end
  
  

  
  def calculate_weights(candidate)
  	  candidate.summaries.each do |summary|
  	  	@score += summary.point
  	  end
  	  return @score
  end

def calculate_mcdm(candidates,job)
  require 'extendmatrix'

    @higher = candidates.desc(:score).limit(1).first
    
    # "School" (Criteria1) + "Company" (Criteria2)
    # Pairwise matrix School = 2 * XP
    @relative=2
    @pairwise_matrix= Matrix.rows([[1, @relative], [1, (1.0/@relative)]])

    #Sum
    @sum1=@pairwise_matrix.row(0).sum
    @sum2=@pairwise_matrix.row(1).sum

    # Weights
    @weight1=@sum1/(@sum1+@sum2)
    @weight2=@sum2/(@sum1+@sum2)

    #Samples




    return @weight1
  
end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  # GET /jobs
  # GET /jobs.json

  def index
    @jobs = Job.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @keywords= Keyword.all
    @job = Job.find(params[:id])
    @candidates = @job.candidates.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
  
  

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,  :rows => 10, :cols => 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<header><%= render 'layouts/header' %></header>
<% if user_signed_in? %>


<div class="menubar"> 
      <ul class="menubarulleft_without">
        <li class="menubaritem">
          <%= link_to "Home", root_path, :class =>'menubarlink' %></li>
      
        <li class="menuaddjob">    <%= link_to image_tag("largebutton.png"), new_job_path, :method => :get, :class => "btn_add"%> </li>

 
      </ul>   
</div>
 
<div class="content">
  <div class="job_content">

<table  class="table">
  <tr class="toptext">
    <td class="title">Title</td>
    <td class="title">Description</td>
    <td class="title">Show</td>
    <td class="title">Edit</td>
    <td class="title">Delete</td>

  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.title %></td>
    <td><%= job.description %></td>
    <td><%= link_to '', job, :class => "icon-eye-open" %></td>
    <td><%= link_to '', edit_job_path(job),:class => "icon-edit" %></td>
    <td><%= link_to '', job, confirm: 'Are you sure?', method: :delete, :class => "icon-trash" %></td>
  </tr>
<% end %>
</table>

  </div>
</div>
   
<!-- Apply part -->
<%else%>
<div class="row">

<div class="span12">
  <ul class="topbar">
    Apply
  </ul>
</div>
</div>

<table  class="table">
  <tr class="toptext">
    <td class="title">Title</td>
    <td class="title">Description</td>
    <td class="title">Show</td>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.title %></td>
    <td><%= job.description %></td>
    <td><%= link_to '', job, :class => "icon-eye-open" %></td>
  </tr>
<% end %>
</table>
<%end%>
<footer><%= render 'layouts/footer' %></footer>

app/views/jobs/mcdm.html.erb
<header><%= render 'layouts/header' %></header>

<h1>MCDM Analysis</h1>

<h3>Criteria Weights</h3>

<table class="table">
       <thead>
      <tr>
        <td><b>Criteria</b></td>
        <td><b>Description</b></td>
        <td><b>Weight</b></td>
       <td> </td>
      
      </tr>
       </thead>
      <% @criteria.order_by([:weight, :desc]).each do |criterium| %>
       <thead>
      <tr>
        <td><%= criterium.name %></td>
        <td><%= criterium.description %></td>
        <td><%= criterium.weight %><%= link_to "Up", vote_up_job_criterium_path(@job, criterium) %> <%= link_to "Down", vote_down_job_criterium_path(@job, criterium) %></td>
      </tr>
       </thead>
    <% end %>
</table>

<%= Mcdm::mcdm(@criteria, @candidates) %>
    

app/views/jobs/new.html.erb
<header><%= render 'layouts/header' %></header>

<div class="menubar"> 
      <ul class="menubarulleft_without">
        <li class="menubaritem">
          <%= link_to "Home", root_path, :class =>'menubarlink' %></li><li class="separator"> </li>
        <li class="menubaritem">Add new job</li>
      </ul>   
</div>

<% if user_signed_in? %>
                  
<div class="content">
  <div class="job_content form_content">
    <%= render 'form' %>
    <%= link_to 'Back', jobs_path %>
  </div>
</div>

<footer><%= render 'layouts/footer' %></footer>
<% else %>
  <%= link_to('Login', new_user_session_path, :class => 'btn btn-large')  %>
  <%= link_to('Sign up', new_user_registration_path, :class => 'btn btn-large')  %>
<% end %>

app/views/jobs/show.html.erb
<header><%= render 'layouts/header' %></header>
<% if user_signed_in? %>

<div class="menubar"> 
      <ul class="menubarulleft">
        <li class="menubaritem">
          <%= link_to "Home", root_path, :class =>'menubarlink' %></li>
        <li class="separator"> </li>
        <li class="menubaritem"><%=@job.title%></li>
        <li class="menuaddcandidate"> <%= button_to "Add candidate", new_job_candidate_path(@job), :method => :get, :class => "btn_add"%>  </li>
      </ul>   
</div>

<div class="content">
  <div class="resume">
   <div class="stat">You have reviewed <%= @candidates.voted_by(current_user).count%> / <%= @candidates.count%> candidates</div>
    <table class="table">
      <tr>
        <td class="title">Name</td>
        <td class="title"> </td>
         <td class="title">Review</td>
      </tr>
      <% @candidates.order_by([:score, :desc]).each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= link_to '',  job_candidate_path(:id => candidate.id, :job_id => @job.id),:class => "icon-eye-open" %></td>
        <td><%=current_user.vote_value(candidate)%></td>
      </tr>

    <% end %>
    </table>
 
  </div>
</div>



<!-- Not logged in part -->


<% else %>
<div class="row">

<div class="span12">
  <ul class="topbar">
 
    Apply
    </ul>
</div>
</div>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>
 <%= button_to "Apply", new_job_candidate_path(@job), :method => :get, :class => "btn"%>

<% end %>
<footer><%= render 'layouts/footer' %></footer>