config/routes.rb
Mvp::Application.routes.draw do

  resources :keywords do 
    	member do
        get :vote_up
        get :vote_down
      end
  end
 
  get "pages/about"
  get "pages/test"
  get "pages/test2"
  get "jobs/autopilot"
  match "/about" => "pages#about"
  match "/apply" => "jobs#index"


  resources :jobs do

  	member do 
  		get 'mcdm'
      get 'autopilot'
  		match 'apply' => "candidates#new"
      match 'autopilot' => "jobs#autopilot"
  	end

  	resources :candidates do
        resources :comments 
  		member do

        get :vote_up
        get :vote_down
      end
    end

    resources :criteria do 
  		member do
        get :vote_up
        get :vote_down
      end
    end
  end

  authenticated :user do
    root :to => 'jobs#index'
  end
  root :to => "users#show"
  devise_for :users
  resources :users, :only => :show

  
end

app/models/candidate.rb
class Candidate
  include Mongoid::Document
  include Mongoid::Paperclip
  include Mongoid::Timestamps
  include Mongo::Voteable

  field :name, :type => String
  field :resume, :type => String
  field :attached_resume
  field :visited, type: Integer, :default => 0
  has_mongoid_attached_file :cv
  field :score, :type => Integer, :default => 0 
  embeds_many :summaries
  embeds_many :comments, :inverse_of => :candidate 
  voteable self, :up => +1, :down => -1
  validates_associated :comments
  validates_presence_of :name, :resume, :cv 
  accepts_nested_attributes_for :comments, :allow_destroy => true

  belongs_to :job


  	def add_resume(submit_cv, keywords)
  		if self.attached_resume.nil? 
  			self.convert_to_txt(submit_cv)
  		end
      #Search for keywords
  		#scan_attached_resume(self)
  		
      	
  	end

    def convert_to_txt(submit_cv)
    
    require 'open-uri'
    io = open(submit_cv)
    reader = PDF::Reader.new(io)
	    reader.pages.each do |page|
	    	self.update_attributes(attached_resume: page.text)
	    end
    end

    def scan_attached_resume(candidate)
    	@keywords = Keyword.all	
    	m= TactfulTokenizer::Model.new
    	@test=m.tokenize_text(candidate.attached_resume)
    	@test.each do |test1|
    		@keywords.each do |keyword|
	            if test1.include?(keyword.name)
	            	if candidate.summaries.empty?
	               		candidate.summaries.create!(description: test1)
	               	end
                  @newscore= candidate.score + keyword.weight
                  candidate.update_attributes(score: @newscore)

	            end
        	end
     	
    	end
    end
def find_next(candidates)
      @ordered_list=candidates.order_by([[:name, :asc]])
      @list_candidate=@ordered_list.where(:name.gt => self.name)
      if @list_candidate.first.nil? == false
       @next_candidate= @list_candidate.first
      else
       @next_candidate=candidates.order_by([[:name, :asc]]).first
      end
      return @next_candidate
end


end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  # GET /candidates
  # GET /candidates.json
  def index
    #@candidates = Candidate.all
    @job = Job.find(params[:job_id])
    @candidates = @job.candidates.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    require 'open-uri'

    @summaries=Summary.all
    @candidate = Candidate.find(params[:id])
    @keywords= Keyword.all
    @candidates = Candidate.all
    @job = Job.find(params[:job_id])
    @comment = @candidate.comments.create!(params[:comment])  

    @next_candidate=@candidate.find_next(@job.candidates)

  

    if @candidate.cv.nil? == false
    	@candidate.add_resume(@candidate.cv.path,@keywords)
    end

    @job = Job.find(params[:job_id]) 
    @keywords= Keyword.all
    @summaries= @candidate.summaries.all
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new
    @job = Job.find(params[:job_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @job = Job.find(params[:job_id])
    @candidate = @job.candidates.build(params[:candidate])
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to(job_candidate_path(@job.id,@candidate.id), :notice => 'Time to organise your resume') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { redirect_to(new_job_candidate_path(@job), :notice => 
        'Candidate could not be saved. Please fill in all fields')}
        format.xml  { render :xml => @candidate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
  
  def vote_up
    @candidate = Candidate.find(params[:id])
    @job = Job.find(params[:job_id])
    current_user.vote(@candidate, :up) 
    redirect_to job_candidate_path(@job.id,@candidate.id), :notice => "You have approved #{@candidate.name} as a suitable candidate"
  end
  
  def vote_down
    @candidate = Candidate.find(params[:id])
    @job = Job.find(params[:job_id])
    current_user.vote(@candidate, :down) 
    redirect_to job_candidate_path(@job.id,@candidate.id), :notice => "You have disapproved #{@candidate.name} as a suitable candidate"
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate, :url => job_candidates_path(@job)) do |f| %>


  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume , :rows => 10, :cols => 25 %>
  </div>
  	<div class="field">
	<%= f.label :cv %><br />
	<%= f.file_field :cv %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', job_candidates_path %>

app/views/candidates/index.html.erb
<%= link_to "Home", root_path %>
<h1>Listing candidates</h1>
Candidates.index
<table>
  <tr>
    <th>Name</th>
    <th>Resume</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.resume %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_job_candidate_path %>

app/views/candidates/new.html.erb
<header><%= render 'layouts/header' %></header>
<div class="menubar"> 
      <ul class="menubarulleft_without">
        <li class="menubaritem">
          <%= link_to "Home", root_path, :class =>'menubarlink' %></li><li class="separator"> </li>
        <li class="menubaritem"><%= link_to @job.title, job_path(@job), :class =>'menubarlink'%></li>
        <li class="separator"> </li>
        <li class="menubaritem">Add new candidate</li>
      </ul>   
</div>
<% if user_signed_in? %>
<div class="content">
 	<div class="job_content form_content">
		<%= render 'form' %>
		<%= link_to 'Back', job_candidates_path %>
	</div>
</div>
<footer><%= render 'layouts/footer' %></footer>

<%else%>
<div class="row">

<div class="span12">
  <ul class="topbar">
 
    Apply forms
    </ul>
</div>
</div>


<%= render 'form' %>

<%end%>

app/views/candidates/show.html.erb
<header><%= render 'layouts/header' %></header>

<div class="menubar"> 
      <ul class="menubarulleft">
        <li class="menubaritem">
          <%= link_to "Home", root_path, :class =>'menubarlink' %></li>
        <li class="separator"> </li>
        <li class="menubaritem"><%= link_to @job.title, job_path(@job), :class =>'menubarlink'%></li>
        <li class="separator"> </li>
        <li class="menubaritem"><%= @candidate.name %></li>
        <li class="menuright">Panel</li>
        <li class="menunext"> <%= link_to image_tag("nextbutton.png"), job_candidate_path(@job,@next_candidate)%>
     
        </li>
      </ul>   
</div>
 
<div class="content">
  <div class="resume">
    <div class="data">
      <div class="name"><%= @candidate.name %></div>
      <div class="links_resume"> <%=  link_to "Resume", @candidate.cv.url,  :target => "_blank"  %> |  <%=  link_to "Cover Letter", root_path  %></div>
      <div class="title">Resume</div>
      <div class="info">
        <%= simple_format(@candidate.attached_resume) %>

      </div>
    </div>
    <div class="panel">
      <div class="panel_title">Approved</div>
      <%= link_to "", vote_up_job_candidate_path(@job, @candidate),:class => "icon-ok" %>  <%= link_to "", vote_down_job_candidate_path(@job, @candidate),:class => "icon-remove" %>
      <br> You (<%= current_user.name %>) have  <%= current_user.vote_value(@candidate) %> this candidate
      <br><br>
      <div class="panel_title">Comments</div>  
      <% if @candidate.comments.size > 0 %>    
      <% for comment in @candidate.comments %> 

        <% if comment.author %><br/><div class="comment_author"><%= comment.author %></div> 
         <% end %>  
        <div class="comment"><%= comment.content %></div> 
      <% end %>  
    <% end %>  
    <br/>
    <div class="panel_title">New comment</div>  

    <%= form_for [@job,@candidate, Comment.new] do |f| %>  
      <p><%= f.text_area :content,:size => "2x5"%></p>  
      <p><%= f.submit %></p>  
    <% end %>  

    </div>

  </div>
</div>
    

<footer><%= render 'layouts/footer' %></footer>