config/routes.rb
Mvp::Application.routes.draw do

  resources :keywords do 
    	member do
        get :vote_up
        get :vote_down
      end
  end
 
  get "pages/about"
  get "pages/test"
  get "pages/test2"
  get "jobs/autopilot"
  match "/about" => "pages#about"
  match "/apply" => "jobs#index"


  resources :jobs do

  	member do 
  		get 'mcdm'
      get 'autopilot'
  		match 'apply' => "candidates#new"
      match 'autopilot' => "jobs#autopilot"
  	end

  	resources :candidates do
        resources :comments 
  		member do

        get :vote_up
        get :vote_down
      end
    end

    resources :criteria do 
  		member do
        get :vote_up
        get :vote_down
      end
    end
  end

  authenticated :user do
    root :to => 'jobs#index'
  end
  root :to => "users#show"
  devise_for :users
  resources :users, :only => :show

  
end

app/models/keyword.rb
class Keyword
  include Mongoid::Document
  field :name, :type => String
  field :weight, :type => Integer
  field :type, :type => String
  field :domain, :type => String
  
  def self.grab_keywords(number)
  	@fake_resume = "Fake resume "
  	@random = Keyword.all.shuffle.slice(0, number)
  	number.times do |i|
  		puts "Cat:" << @random[i].name 
  		@fake_resume << @random[i].name << " .\n"
  	end
  	return @fake_resume
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keywords }
    end
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/new
  # GET /keywords/new.json
  def new
    @keyword = Keyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/1/edit
  def edit
    @keyword = Keyword.find(params[:id])
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(params[:keyword])

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render json: @keyword, status: :created, location: @keyword }
      else
        format.html { render action: "new" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keywords/1
  # PUT /keywords/1.json
  def update
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      if @keyword.update_attributes(params[:keyword])
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end
  
  def vote_up
    @keyword = Keyword.find(params[:id])
    @keyword.inc(:weight, 1)
    redirect_to keywords_url, :notice => "Vote up is successfully submitted."
  end
  
  def vote_down
    @keyword = Keyword.find(params[:id])
    @keyword.inc(:weight, -1)
    redirect_to keywords_url, :notice => "Vote down is successfully submitted."
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

</br>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.order_by([:weight, :desc]).each do |keyword| %>
  <tr>
    <td><%= keyword.name %></td>
    <td><%= keyword.type %></td>
    <td><%= keyword.weight %><%= link_to "Up", vote_up_keyword_path(keyword) %> <%= link_to "Down", vote_down_keyword_path(keyword) %></td>
    <td><%= link_to 'Show', keyword %></td>
    <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
    <td><%= link_to 'Destroy', keyword, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @keyword.name %>
</p>

<p>
  <b>Weight:</b>
  <%= @keyword.weight %>
</p>


<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>